Support GHES
actions/create-github-app-token pull request #36
Opened 2023-08-28 22:52 UTC by 7Hazard

This adds support for this action to be used in GitHub Enterprise Server.
It sends request to the base url extracted from [GITHUB_API_URL](https://docs.github.com/en/enterprise-server@3.10/actions/learn-github-actions/variables#default-environment-variables).

2023-08-28 22:54 UTC, gr2m requested changes
Thanks!

the same change needs to be added to https://github.com/actions/create-github-app-token/blob/17cde8a7d84fe69209226a73af1acac6c76392d5/lib/post.js#L15-L19

No need to update `dist/` files, they will be updated automatically as part of the release. But also no problem if you do.

2023-08-28 22:57 UTC, gr2m requested changes
sorry actually what we need to do is to pass `request.defaults({ baseUrl: process.env.GITHUB_API_URL })` in both `/main.js` and `/post.js`

<img width="908" alt="image" src="https://github.com/actions/create-github-app-token/assets/39992/3d2c93b6-89e7-43d1-b57e-3b7aa855a437">

2023-08-29 15:39 UTC, gr2m approved these changes
Let us know if you have any more questions or concerns, otherwise this is good to go

2023-08-29 18:11 UTC, gr2m commented
We will address the failing CI in pull requests coming from fork via https://github.com/actions/create-github-app-token/issues/32. 

If you like you can build the dist files and try the changes with `uses: 7Hazard/create-github-app-token` and see if it works for you on GHES. But we can also just merge, I'm quite certain that it will work.

2023-08-29 22:53 UTC, 7Hazard commented
> I pushed a change to your pull request because I figured it will be easier to convey what I meant, I hope you don't mind: [c209b0b](https://github.com/actions/create-github-app-token/commit/c209b0b69cc795f9fe7d5de5fce8a1d7496d49ab)
> 
> Calling `request.defaults({ baseUrl: process.env["GITHUB_API_URL"] })` has no side effects, it does not mutate the current `request` instance, it returns a new one with the defaults set

Ah I see, my bad. I didn't research about `requests.default` before using it. Appreciate this push! Feel free to merge it when you want to, whether it before or after the status checks.

2023-08-29 23:04 UTC, parkerbxyz approved these changes

2023-08-29 23:13 UTC, merged